### ISSUE TITLE
Tests run under wrong Python (Windows)

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/system#17]
As discovered in https://github.com/coherent-oss/coherent.build/issues/3#issuecomment-2322741821, the test runners on Windows for Python 3.12 are using Python 3.9 to run the tests.

**Comment by jaraco** [comment]
This issue has largely been solved by https://github.com/coherent-oss/system/commit/518bcf3f4d0a826022de0a993f25cb9b84382952.

However, there are still [some failures](https://github.com/coherent-oss/coherent.build/actions/runs/10745376162/job/29806882533) on Python 3.12 due to how pipx is provisioned with an incomplete copy of setuptools:

```
Run pipx run --python 3.12 'coherent.test>=0.7.0'
creating virtual environment...
installing coherent-test from spec 'coherent-test>=0.7.0'...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/coherent/test/__main__.py", line 8, in <module>
    from coherent.build import bootstrap
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/coherent/build/__init__.py", line 8, in <module>
    from .backend import (
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/coherent/build/backend.py", line 20, in <module>
    from .metadata import Message
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/coherent/build/metadata.py", line 18, in <module>
    from . import discovery
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/coherent/build/discovery.py", line 21, in <module>
    import setuptools_scm
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/setuptools_scm/__init__.py", line 8, in <module>
    from ._config import DEFAULT_LOCAL_SCHEME
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/setuptools_scm/_config.py", line 17, in <module>
    from ._integration.pyproject_reading import (
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/setuptools_scm/_integration/pyproject_reading.py", line 9, in <module>
    from .setuptools import read_dist_name_from_setup_cfg
  File "/opt/pipx/.cache/d1eeadd94b582be/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py", line 10, in <module>
    import setuptools
  File "/opt/pipx/shared/lib/python3.10/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
```

As you can see, Setuptools is present, but somehow from python 3.10. I'm guessing whoever installs Setuptools on Python 3.10 removes the distutils shim in order to rely on distutils from stdlib, but by the time we're on Python 3.12, there is no such thing.

The issue only seems to affect Windows and Linux but not macOS. Sheesh.

**Comment by jaraco** [comment]
In order to troubleshoot, we're going to have to somehow understand more about how the CI images are built and how the Setup Python actions work to configure Python and Pipx on these systems.

**Comment by webknjaz** [comment]
https://github.com/actions/runner-images
